# Generated by Django 6.0 on 2026-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
